### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by stuaxo** [pussinboot/mdvj#1]
I started a setup.py   ...  pywin32 and pygame were a bit of a bugger to get installing, but I managed it.

After that I realised I don't have a midi device ... will this work with a software midi controller ?

It's best if you move all the other code into an 'mdvj' folder, then uncomment the packages part, it should install OK then.

```
from setuptools import setup

long_description="""
mdvj v0.0.2 - milkdrop vj midi controller
for use with novation twitch controller
"""
import sys;

is64bit = sys.maxsize > 2**32
if is64bit:
    pygame_whl="http://www.lfd.uci.edu/~gohlke/pythonlibs/z94jfosk/pygame-1.9.2a0-cp34-none-win_amd64.whl#egg=pygame-1.9"
else:
    pygame_whl="http://www.lfd.uci.edu/~gohlke/pythonlibs/z94jfosk/pygame-1.9.2a0-cp34-none-win32.whl#egg=pygame-1.9"

setup(
    name='mdvj',
    version='0.0.2',

    description='Milkdrop DJ Tool',
    long_description=long_description,
    url='https://github.com/pussinboot/mdvj',

    keywords='vj midi novation',
    #packages=['mdvj'],

    install_requires=[
        "Pillow",
        "pypiwin32",
    ],

    dependency_links=[
        pygame_whl
    ],

    entry_points = {
            'console_scripts': [
                'mdvj = mdvj:main'
            ]
        },
)
```

**Comment by stuaxo** [comment]
Looks like the pygame uris should be changed to these ones:  https://testpypi.python.org/pypi/pygame/1.9.2a0

**Comment by pussinboot** [comment]
hey,

thanks for the setup.py suggestion, will do.
this should work with any midi controller even software, you'll just have
to figure out what input number it is (line 43 in mdvj.py)
I'll add a flag for controllers that are not the twitch as well.
expect a commit with the changes in the next couple of days, thanks for
checking out my project :)

-leo

**Comment by stuaxo** [comment]
Pants, it still doesn't quite work (latest git) ... thought I had the pygame installation sorted, but today can't get it to work (refereshed my VM).

I guess we need to see if pygame will upload their .whl to the non-test pypi.

pywin32 doesn't seem to need the dependency bit, it just needs 'pypiwin32' in  install_requires.

If you know of any software midi controller that looks appropriate let me know, I'm new to MIDI and VJ software, but am trying to make my own VJ software too.

(A video showing usage of this would be awesome).

**Comment by pussinboot** [comment]
yea, installing pygame and pywin32 can be a pain, I got them from the
unofficial windows binaries for python extension packages.

pypiwin32 in install_requires broke install.py on my system.

not sure about any software midi controllers that would effectively
replicate the layout of a dj controller, instead I'm going to let the
program work just with mouse clicks in the next version :)

video coming soon
