### ISSUE TITLE
Can I still get precompiled version link is down?

### ISSUE THREAD

**Issue by DavidsonAudioMulti** [pussinboot/mdvj#2]
Can I still get precompiled version link is down?

**Comment by pussinboot** [comment]
apologies for the link rot, here's the same zip:
https://github.com/pussinboot/mdvj/releases/download/0.5.1/mdvj_v_0_5_1.zip
tested and made sure it still works lol

**Comment by DavidsonAudioMulti** [comment]
Thank you!!

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
